DRA: Improve kubelet version selection logic
Instead of assuming the previous stable release always exists,
check for its presence and fall back to the latest release
if necessary.

diff --git a/config/jobs/kubernetes/sig-node/dra-canary.yaml b/config/jobs/kubernetes/sig-node/dra-canary.yaml
--- a/config/jobs/kubernetes/sig-node/dra-canary.yaml
+++ b/config/jobs/kubernetes/sig-node/dra-canary.yaml
@@ -334,8 +334,20 @@ presubmits:
           major=$(echo "$revision" | sed -e 's/^v\([0-9]*\).*/\1/')
           minor=$(echo "$revision" | sed -e 's/^v[0-9]*\.\([0-9]*\).*/\1/')
           previous_minor=$((minor - 1))
-          # Test with the lastest stable release to avoid breaking presubmits because of unrelated issues in a release candidate.
-          previous=$(curl --silent -L "https://dl.k8s.io/release/stable-$major.$previous_minor.txt" )
+          # Test with the stable release to avoid breaking presubmits because of unrelated issues in a release candidate.
+          response=$(curl --silent -w '%{http_code}' -L "https://dl.k8s.io/release/stable-$major.$previous_minor.txt" )
+          status="${response: -3}"
+          previous="${response::-3}"
+          if [ status == 404 ] ; then
+              # if stable doesn't exist - use latest
+              response=$(curl --silent -w '%{http_code}' -L "https://dl.k8s.io/release/latest-$major.$previous_minor.txt" )
+              status="${response: -3}"
+              previous="${response::-3}"
+          fi
+          if [ status -ne 200 ] ; then
+              echo "error: unable to get release $major.$previous_minor info"
+              exit 1
+          fi
           curl --silent -L "https://dl.k8s.io/release/$previous/kubernetes-server-linux-amd64.tar.gz" | tar zxOf - kubernetes/server/bin/kubelet >/tmp/kubelet
           chmod a+rx /tmp/kubelet
           /tmp/kubelet --version
@@ -447,8 +459,20 @@ presubmits:
           major=$(echo "$revision" | sed -e 's/^v\([0-9]*\).*/\1/')
           minor=$(echo "$revision" | sed -e 's/^v[0-9]*\.\([0-9]*\).*/\1/')
           previous_minor=$((minor - 2))
-          # Test with the lastest stable release to avoid breaking presubmits because of unrelated issues in a release candidate.
-          previous=$(curl --silent -L "https://dl.k8s.io/release/stable-$major.$previous_minor.txt" )
+          # Test with the stable release to avoid breaking presubmits because of unrelated issues in a release candidate.
+          response=$(curl --silent -w '%{http_code}' -L "https://dl.k8s.io/release/stable-$major.$previous_minor.txt" )
+          status="${response: -3}"
+          previous="${response::-3}"
+          if [ status == 404 ] ; then
+              # if stable doesn't exist - use latest
+              response=$(curl --silent -w '%{http_code}' -L "https://dl.k8s.io/release/latest-$major.$previous_minor.txt" )
+              status="${response: -3}"
+              previous="${response::-3}"
+          fi
+          if [ status -ne 200 ] ; then
+              echo "error: unable to get release $major.$previous_minor info"
+              exit 1
+          fi
           curl --silent -L "https://dl.k8s.io/release/$previous/kubernetes-server-linux-amd64.tar.gz" | tar zxOf - kubernetes/server/bin/kubelet >/tmp/kubelet
           chmod a+rx /tmp/kubelet
           /tmp/kubelet --version
