Add per pr testing for GKE against GCI image
Job, GCE Project
`kubernetes-pull-build-test-gci-e2e-gke`,`k8s-jkns-pr-gci-gke`

diff --git a/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml b/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml
--- a/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml
+++ b/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml
@@ -152,6 +152,70 @@
                 fi
                 echo "Exiting with code: ${{rc}}"
                 exit ${{rc}}
+        - 'gci-e2e-gke': # kubernetes-pull-build-test-gci-e2e-gke
+            cmd: |
+                case "${{ghprbTargetBranch:-}}" in
+                  release-1.0|release-1.1|release-1.2)
+                    echo "PR GKE job disabled for legacy branches."
+                    exit
+                    ;;
+                esac
+                export KUBE_SKIP_PUSH_GCS=n
+                export KUBE_GCS_RELEASE_BUCKET=kubernetes-release-pull
+                export KUBE_RUN_FROM_OUTPUT=y
+                export KUBE_FASTBUILD=true
+                export KUBE_GCS_UPDATE_LATEST=n
+                ./hack/jenkins/build.sh
+                version=$(source build/util.sh && echo $(kube::release::semantic_version))
+                gsutil -m rsync -r "gs://kubernetes-release-pull/ci/${{version}}" "gs://kubernetes-release-dev/ci/${{version}}-pull"
+                # Strip off the leading 'v' from the cluster version.
+                export CLUSTER_API_VERSION="${{version:1}}-pull"
+                # Nothing should want Jenkins $HOME
+                export HOME=${{WORKSPACE}}
+                export KUBERNETES_PROVIDER="gke"
+                export E2E_MIN_STARTUP_PODS="1"
+                export FAIL_ON_GCP_RESOURCE_LEAK="true"
+                # Flake detection. Individual tests get a second chance to pass.
+                export GINKGO_TOLERATE_FLAKES="y"
+                export E2E_NAME="e2e-gke-${{NODE_NAME}}-${{EXECUTOR_NUMBER}}"
+                export GINKGO_PARALLEL="y"
+                # Just run a smoke test.
+                export GINKGO_TEST_ARGS="--ginkgo.focus=Guestbook"
+                export FAIL_ON_GCP_RESOURCE_LEAK="false"
+                export PROJECT="k8s-jkns-pr-gci-gke"
+                # Since we're only running one test, just use two nodes.
+                export NUM_NODES="2"
+                # Assume we're upping, testing, and downing a cluster
+                export E2E_UP="true"
+                export E2E_TEST="true"
+                export E2E_DOWN="true"
+                export E2E_OPT="--check_version_skew=false"
+                # Force to use container-vm.
+                export KUBE_NODE_OS_DISTRIBUTION="gci"
+                # Skip gcloud update checking
+                export CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true
+                # GKE variables
+                export CLUSTER_NAME=${{E2E_NAME}}
+                export KUBE_GKE_NETWORK=${{E2E_NAME}}
+                export ZONE="us-central1-f"
+                export CLOUDSDK_API_ENDPOINT_OVERRIDES_CONTAINER="https://test-container.sandbox.googleapis.com/"
+                export CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=False
+                # Get golang into our PATH so we can run e2e.go
+                export PATH=${{PATH}}:/usr/local/go/bin
+                timeout -k 15m 55m {runner} && rc=$? || rc=$?
+                if [[ ${{rc}} -ne 0 ]]; then
+                  if [[ -x cluster/log-dump.sh && -d _artifacts ]]; then
+                    echo "Dumping logs for any remaining nodes"
+                    ./cluster/log-dump.sh _artifacts
+                  fi
+                fi
+                if [[ ${{rc}} -eq 124 || ${{rc}} -eq 137 ]]; then
+                  echo "Build timed out" >&2
+                elif [[ ${{rc}} -ne 0 ]]; then
+                  echo "Build failed" >&2
+                fi
+                echo "Exiting with code: ${{rc}}"
+                exit ${{rc}}
         - 'gci-e2e-gce': # kubernetes-pull-build-test-gci-e2e-gce
             cmd: |
                 export KUBE_SKIP_PUSH_GCS=y
