Add GCI testing for kubernetes-pull-build-test-e2e-gce
Job,GCE Project
`kubernetes-pull-gci-build-test-e2e-gce`,`k8s-jkns-pr-gci-gce`

diff --git a/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml b/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml
--- a/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml
+++ b/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml
@@ -150,6 +150,68 @@
                 fi
                 echo "Exiting with code: ${{rc}}"
                 exit ${{rc}}
+        - 'gci-build-test-e2e-gce': # kubernetes-pull-gci-build-test-e2e-gce
+            cmd: |
+                export KUBE_SKIP_PUSH_GCS=y
+                export KUBE_RUN_FROM_OUTPUT=y
+                export KUBE_FASTBUILD=true
+                ./hack/jenkins/build.sh
+                if [[ "${{ghprbTargetBranch:-}}" == "release-1.0" || "${{ghprbTargetBranch:-}}" == "release-1.1" ]]; then
+                  ./hack/jenkins/e2e.sh
+                else
+                  # Nothing should want Jenkins $HOME
+                  export HOME=${{WORKSPACE}}
+
+                  export KUBERNETES_PROVIDER="gce"
+                  export E2E_MIN_STARTUP_PODS="1"
+                  export KUBE_GCE_ZONE="us-central1-f"
+                  export FAIL_ON_GCP_RESOURCE_LEAK="true"
+
+                  # Flake detection. Individual tests get a second chance to pass.
+                  export GINKGO_TOLERATE_FLAKES="y"
+
+                  export E2E_NAME="e2e-gce-${{NODE_NAME}}-${{EXECUTOR_NUMBER}}"
+                  export GINKGO_PARALLEL="y"
+                  # This list should match the list in kubernetes-e2e-gce.
+                  export GINKGO_TEST_ARGS="--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]"
+                  export FAIL_ON_GCP_RESOURCE_LEAK="false"
+                  export PROJECT="k8s-jkns-pr-gci-gce"
+                  # NUM_NODES should match kubernetes-e2e-gce.
+                  export NUM_NODES="3"
+
+                  # Force to use container-vm.
+                  export KUBE_NODE_OS_DISTRIBUTION="gci"
+                  # Assume we're upping, testing, and downing a cluster
+                  export E2E_UP="true"
+                  export E2E_TEST="true"
+                  export E2E_DOWN="true"
+
+                  # Skip gcloud update checking
+                  export CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true
+
+                  # GCE variables
+                  export INSTANCE_PREFIX=${{E2E_NAME}}
+                  export KUBE_GCE_NETWORK=${{E2E_NAME}}
+                  export KUBE_GCE_INSTANCE_PREFIX=${{E2E_NAME}}
+
+                  # Get golang into our PATH so we can run e2e.go
+                  export PATH=${{PATH}}:/usr/local/go/bin
+
+                  timeout -k 15m 55m {runner} && rc=$? || rc=$?
+                  if [[ ${{rc}} -ne 0 ]]; then
+                    if [[ -x cluster/log-dump.sh && -d _artifacts ]]; then
+                      echo "Dumping logs for any remaining nodes"
+                      ./cluster/log-dump.sh _artifacts
+                    fi
+                  fi
+                  if [[ ${{rc}} -eq 124 || ${{rc}} -eq 137 ]]; then
+                    echo "Build timed out" >&2
+                  elif [[ ${{rc}} -ne 0 ]]; then
+                    echo "Build failed" >&2
+                  fi
+                  echo "Exiting with code: ${{rc}}"
+                  exit ${{rc}}
+                fi
         - 'federation-e2e-gce': # kubernetes-pull-build-test-federation-e2e-gce
             cmd: |
                 # Federation specific params
