Adding kubemark job to pr builder

diff --git a/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml b/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml
--- a/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml
+++ b/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml
@@ -542,6 +542,58 @@
             echo "Exiting with code: ${{rc}}"
             exit ${{rc}}
 
+      - build-test-kubemark-e2e-gce: # kubernetes-pull-build-test-kubemark-e2e-gce
+          status-context: Kubemark GCE e2e
+          max-total: 12
+          only-trigger-phrase: true  # This test should run only if explicitly triggered.
+          trigger-phrase: 'kubemark\s+test'
+          cmd: |
+            export KUBE_SKIP_PUSH_GCS=y
+            export KUBE_RUN_FROM_OUTPUT=y
+            export KUBE_FASTBUILD=true
+            ./hack/jenkins/build.sh
+
+            # Nothing should want Jenkins $HOME
+            export HOME=${{WORKSPACE}}
+
+            export KUBERNETES_PROVIDER="gce"
+            export E2E_NAME="e2e-kubemark-${{NODE_NAME}}-${{EXECUTOR_NUMBER}}"
+            export PROJECT="k8s-jkns-pr-kubemark"
+            export E2E_TEST="false"
+            export USE_KUBEMARK="true"
+            export KUBEMARK_TESTS="starting\s30\spods\sper\snode"
+            export FAIL_ON_GCP_RESOURCE_LEAK="false"
+            # Override defaults to be independent from GCE defaults and set kubemark parameters
+            export NUM_NODES="1"
+            export MASTER_SIZE="n1-standard-1"
+            export NODE_SIZE="n1-standard-2"
+            export KUBE_GCE_ZONE="us-central1-f"
+            export KUBEMARK_MASTER_SIZE="n1-standard-1"
+            export KUBEMARK_NUM_NODES="5"
+            # The kubemark scripts build a Docker image
+            export JENKINS_ENABLE_DOCKER_IN_DOCKER="y"
+
+            # Skip gcloud update checking
+            export CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true
+
+            # Get golang into our PATH so we can run e2e.go
+            export PATH=${{PATH}}:/usr/local/go/bin
+
+            timeout -k 15m 45m ./hack/jenkins/e2e-runner.sh && rc=$? || rc=$?
+            if [[ ${{rc}} -ne 0 ]]; then
+              if [[ -x cluster/log-dump.sh && -d _artifacts ]]; then
+                echo "Dumping logs for any remaining nodes"
+                ./cluster/log-dump.sh _artifacts
+              fi
+            fi
+            if [[ ${{rc}} -eq 124 || ${{rc}} -eq 137 ]]; then
+              echo "Build timed out" >&2
+            elif [[ ${{rc}} -ne 0 ]]; then
+              echo "Build failed" >&2
+            fi
+            echo "Exiting with code: ${{rc}}"
+            exit ${{rc}}
+
     jobs:
         - '{git-project}-pull-{suffix}'
 
