[ci-kubernetes-e2e-kind-dependencies] Run depstat before and after updating deps
move things around a bit.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

diff --git a/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml b/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml
--- a/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml
+++ b/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml
@@ -563,12 +563,22 @@ periodics:
         set -o pipefail
         set -o xtrace
 
+        # install kind
+        curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/"
+
+        # install depstat
         export WORKDIR=${ARTIFACTS:-$TMPDIR}
         export PATH=$PATH:$GOPATH/bin
         mkdir -p "${WORKDIR}"
+        pushd "$WORKDIR"
+        go install github.com/kubernetes-sigs/depstat@latest
+        popd
 
         # needed by gomod_staleness.py
         apt update && apt -y install jq
+
+        # grab the stats before we start
+        depstat stats -m "k8s.io/kubernetes$(ls staging/src/k8s.io | awk '{printf ",k8s.io/" $0}')" -v > "${WORKDIR}/stats-before.txt"
 
         # Update each dependency to the latest version
         ./../test-infra/experiment/dependencies/gomod_staleness.py
@@ -576,17 +586,18 @@ periodics:
         # See if update-vendor still works
         hack/update-vendor.sh
 
+        # gather stats for comparison after running update-vendor
+        depstat stats -m "k8s.io/kubernetes$(ls staging/src/k8s.io | awk '{printf ",k8s.io/" $0}')" -v > "${WORKDIR}/stats-after.txt"
+        diff -s -u --ignore-all-space "${WORKDIR}"/stats-before.txt "${WORKDIR}"/stats-after.txt || true
+
         # Do not worry if this fails, it is bound to fail
         hack/lint-dependencies.sh || true
 
-        # gather stats for comparison
-        pushd "$WORKDIR"
-        go install github.com/kubernetes-sigs/depstat@latest
-        popd
-        depstat stats -m "k8s.io/kubernetes$(ls staging/src/k8s.io | awk '{printf ",k8s.io/" $0}')" --json | tee "${WORKDIR}/stats-base.json";
+        # Do not worry if this fails, it is bound to fail
+        hack/verify-typecheck.sh || true
 
-        # if we got this far, let's run the tests too!
-        curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
+        # run kind based tests
+        e2e-k8s.sh || true
       env:
       - name: LABEL_FILTER
         value: "Feature: isEmpty && !Slow && !Disruptive && !Flaky"
