New CI job - Improve visibility to upcoming dependency issues
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

diff --git a/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml b/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml
--- a/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml
+++ b/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml
@@ -528,6 +528,80 @@ periodics:
 
 - interval: 4h
   cluster: k8s-infra-prow-build
+  name: ci-kubernetes-e2e-kind-dependencies
+  annotations:
+    testgrid-dashboards: sig-testing-kind
+    testgrid-tab-name: kind-master-dependencies
+    description: Runs tests after updating dependencies to latest versions
+    testgrid-alert-email: davanum@gmail.com
+    testgrid-num-columns-recent: '6'
+  labels:
+    preset-dind-enabled: "true"
+    preset-kind-volume-mounts: "true"
+  decorate: true
+  decoration_config:
+    timeout: 60m
+  extra_refs:
+  - org: kubernetes
+    repo: kubernetes
+    base_ref: master
+    path_alias: k8s.io/kubernetes
+  - org: kubernetes
+    repo: test-infra
+    base_ref: master
+    path_alias: k8s.io/test-infra
+  spec:
+    containers:
+    - image: gcr.io/k8s-staging-test-infra/krte:v20250513-98d205aae3-master
+      command:
+      - wrapper.sh
+      - bash
+      - -c
+      - |
+        set -o errexit
+        set -o nounset
+        set -o pipefail
+        set -o xtrace
+
+        export WORKDIR=${ARTIFACTS:-$TMPDIR}
+        export PATH=$PATH:$GOPATH/bin
+        mkdir -p "${WORKDIR}"
+
+        # Update each dependency to the latest version
+        ./../test-infra/experiment/gomod_staleness.py
+
+        # See if update-vendor still works
+        hack/update-vendor.sh
+
+        # Do not worry if this fails, it is bound to fail
+        hack/lint-dependencies.sh || true
+
+        # gather stats for comparison
+        pushd "$WORKDIR"
+        go install github.com/kubernetes-sigs/depstat@latest
+        popd
+        depstat stats -m "k8s.io/kubernetes$(ls staging/src/k8s.io | awk '{printf ",k8s.io/" $0}')" --json | tee "${WORKDIR}/stats-base.json";
+
+        # if we got this far, let's run the tests too!
+        curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
+      env:
+      - name: LABEL_FILTER
+        value: "Feature: isEmpty && !Slow && !Disruptive && !Flaky"
+      - name: PARALLEL
+        value: "true"
+      # we need privileged mode in order to do docker in docker
+      securityContext:
+        privileged: true
+      resources:
+        limits:
+          cpu: 7
+          memory: 9000Mi
+        requests:
+          cpu: 7
+          memory: 9000Mi
+
+- interval: 4h
+  cluster: k8s-infra-prow-build
   name: ci-kubernetes-e2e-kind-beta-features
   annotations:
     testgrid-dashboards: sig-release-master-informing, sig-testing-kind
